const menuData = [
    { id: 1, nama: "Nasi Putih", kategori: "Makanan Pokok", kalori: 180, harga: 5000, gambar: "images/mie1.jfif" },
    { id: 2, nama: "Nasi Goreng Spesial", kategori: "Makanan Pokok", kalori: 450, harga: 18000, gambar: "images/mie2.jfif" },
    { id: 3, nama: "Mie Goreng Jawa", kategori: "Makanan Pokok", kalori: 380, harga: 16000, gambar: "images/mie3.jfif" },
    { id: 4, nama: "Spaghetti Aglio Olio", kategori: "Makanan Pokok", kalori: 420, harga: 28000, gambar: "spaghetti.jpg" },
    { id: 5, nama: "Kentang Panggang", kategori: "Makanan Pokok", kalori: 220, harga: 15000, gambar: "kentang.jpg" },
    { id: 6, nama: "Roti Gandum (2 lembar)", kategori: "Makanan Pokok", kalori: 160, harga: 8000, gambar: "roti-gandum.jpg" },
    { id: 7, nama: "Ayam Goreng Tepung", kategori: "Lauk-Pauk", kalori: 300, harga: 17000, gambar: "ayam-goreng.jpg" },
    { id: 8, nama: "Ayam Bakar Madu", kategori: "Lauk-Pauk", kalori: 280, harga: 20000, gambar: "ayam-bakar.jpg" },
    { id: 9, nama: "Rendang Daging Sapi", kategori: "Lauk-Pauk", kalori: 380, harga: 32000, gambar: "rendang.jpg" },
    { id: 10, nama: "Tempe Orek", kategori: "Lauk-Pauk", kalori: 150, harga: 8000, gambar: "tempe-orek.jpg" },
    { id: 11, nama: "Tahu Goreng", kategori: "Lauk-Pauk", kalori: 120, harga: 6000, gambar: "tahu-goreng.jpg" },
    { id: 12, nama: "Ikan Nila Bakar", kategori: "Lauk-Pauk", kalori: 250, harga: 22000, gambar: "nila-bakar.jpg" },
    { id: 13, nama: "Telur Dadar", kategori: "Lauk-Pauk", kalori: 190, harga: 7000, gambar: "telur-dadar.jpg" },
    { id: 14, nama: "Beef Steak Sirloin", kategori: "Lauk-Pauk", kalori: 420, harga: 45000, gambar: "beef-steak.jpg" },
    { id: 15, nama: "Tumis Kangkung", kategori: "Sayur", kalori: 90, harga: 9000, gambar: "tumis-kangkung.jpg" },
    { id: 16, nama: "Sayur Asem", kategori: "Sayur", kalori: 70, harga: 8000, gambar: "sayur-asem.jpg" },
    { id: 17, nama: "Capcay Kuah", kategori: "Sayur", kalori: 110, harga: 13000, gambar: "capcay.jpg" },
    { id: 18, nama: "Salad Sayur Segar", kategori: "Sayur", kalori: 80, harga: 14000, gambar: "salad-sayur.jpg" },
    { id: 19, nama: "Gado-Gado", kategori: "Sayur", kalori: 280, harga: 16000, gambar: "gado-gado.jpg" },
    { id: 20, nama: "Pisang (1 buah)", kategori: "Buah", kalori: 105, harga: 5000, gambar: "pisang.jpg" },
    { id: 21, nama: "Apel Fuji (1 buah)", kategori: "Buah", kalori: 95, harga: 7000, gambar: "apel.jpg" },
    { id: 22, nama: "Semangka (1 potong)", kategori: "Buah", kalori: 60, harga: 6000, gambar: "semangka.jpg" },
    { id: 23, nama: "Fruit Salad Cup", kategori: "Buah", kalori: 140, harga: 17000, gambar: "fruit-salad.jpg" },
    { id: 24, nama: "Es Teh Manis", kategori: "Minuman", kalori: 90, harga: 5000, gambar: "es-teh.jpg" },
    { id: 25, nama: "Air Mineral 600ml", kategori: "Minuman", kalori: 0, harga: 4000, gambar: "air-mineral.jpg" },
    { id: 26, nama: "Jus Alpukat", kategori: "Minuman", kalori: 230, harga: 18000, gambar: "jus-alpukat.jpg" }
];